# Generated by Django 4.2.7 on 2023-11-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringers',
            name='sport',
            field=models.IntegerField(choices=[(1, 'Badminton'), (2, 'Tennis'), (3, 'Squash')], default=1),
            preserve_default=False,
        ),
    ]
