# Generated by Django 4.2.7 on 2023-11-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_stringers_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('streetAddress', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=2)),
                ('postalCode', models.CharField(max_length=6)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('dateOfBirth', models.DateField()),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
